development:
    adapter: postgresql
    encoding: unicode
    database: blog_development
    pool: 5
    username: benwilliams
    password:
    timeout: 5000

test:
    adapter: postgresql
    encoding: unicode
    database: blog_test
    pool: 5
    username: benwilliams
    password:
    timeout: 5000
